trigger: none

variables:
- group: toDo-App

stages:
    # - stage: SoftwareCompositionAnalysis
    #   displayName: Software Composition Analysis

    #   jobs:
    #   - job: DependencyVulnerabilityScan
    #     displayName: Dependency Vulnerability Scan (Retire.js)

    #     steps:
    #     - task: PowerShell@2
          
    #       inputs:
    #         targetType: 'inline'
    #         script: |
    #             cd $(frontendPath)
    #             npm install
    #             npm install --save-dev retire
    #             npx   retire --outputformat json --outputpath retire-report.json --severity high
            
    #       displayName: 'Retire.js Install and Run'

    # - stage: StaticCodeAnalysis
    #   displayName: Static Code Analysis (SonarQube)

    #   jobs:
    #       - job: SonarQubeScan
    #         displayName: SonarQube Scan

    #         steps:
    #         - task: SonarQubePrepare@8
    #           inputs:
    #             SonarQube: 'SonarCloud'
    #             scannerMode: 'cli'
    #             configMode: 'manual'
    #             cliProjectKey: 'BhabyaBharti_ToDo-App'
    #             cliProjectName: 'ToDo-App'
    #             cliSources: '.'
    #             extraProperties: |
    #               sonar.organization=bhabyabharti
    #               sonar.host.url=https://sonarcloud.io
    #               sonar.tests=
    #               sonar.test.exclusions=**/*

    #         - task: SonarQubeAnalyze@8
    #           continueOnError: true
    #           inputs:
    #             jdkversion: 'JAVA_HOME_17_X64'

    #         - task: SonarQubePublish@8
    #           inputs:
    #             pollingTimeoutSec: '300'

    # - stage: CodeQualityChecks
    #   displayName: Code Quality & Linting

    #   jobs:
    #   - job: LintFrontend
    #     displayName: 'Lint React Frontend'

    #     steps:
    #     - task: NodeTool@0
    #       inputs:
    #         versionSource: 'spec'
    #         versionSpec: '18.x'
    #       displayName: 'Install NodeJS'

    #     # - task: PowerShell@2
    #     #   displayName: Install and Run HTMLHint
    #     #   inputs:
    #     #     targetType: 'inline'
    #     #   script: |
    #     #     cd $(frontendPath/src)       
    #     #     npm install       
    #     #     # Install HTMLHint if not in package.json (run locally once and commit)       
    #     #     npm install --save-dev htmlhint
    #     #     npx htmlhint "**/*.html"
        
    #     #   displayName: 'HTMLHint Run'
        
    #     - task: PowerShell@2
    #       displayName: Install and Run Biome
    #       continueOnError: true
    #       inputs:
    #         targetType: 'inline'
    #         script: |

    #           Invoke-WebRequest -Uri "https://github.com/biomejs/biome/releases/download/%40biomejs%2Fbiome%402.3.8/biome-win32-x64.exe" -OutFile "$(Agent.ToolsDirectory)/biome.exe"
    #           $(Agent.ToolsDirectory)/biome.exe lint $(frontendpath)/src/

    #     - task: PowerShell@2
    #       continueOnError: true
    #       inputs:
    #         targetType: 'inline'
    #         script: |
    #           Write-Host "Initializing npm project..."
    #           npm init -y

    #           Write-Host "Installing Stylelint..."
    #           npm install --save-dev stylelint stylelint-config-standard stylelint-config-recommended

    #           Write-Host "Creating .stylelintrc.json..."

    #           $config = @{
    #             extends = @(
    #               "stylelint-config-standard"
    #               "stylelint-config-recommended"
    #             )
    #           }

    #           $config | ConvertTo-Json -Depth 5 | Out-File ".stylelintrc.json" -Encoding utf8

    #           Write-Host "Running Stylelint..."
    #           npx stylelint "**/*.css" "**/*.scss"

    #           exit 0

    #       displayName: Install and Run StyleLint

    #     - task: PowerShell@2
    #       continueOnError: true
    #       inputs:
    #         targetType: 'inline'
    #         script: |
    #           cd $(frontendPath)
    #             npm install
    #             # Install lint tools if not in package.json (run locally once and commit)
    #             npm install --save-dev eslint @eslint/js globals eslint-plugin-react eslint-config-standard 
    #             npx eslint src/ --ext .js,.jsx,.ts,.tsx
    #             npx stylelint "**/*.css"
    #             npx biome lint ./src

    #       displayName: 'Install and Run ESLint'

    #     - task: PowerShell@2
    #       continueOnError: true
    #       inputs:
    #         targetType: 'inline'
    #         script: |
    #           npm install -g markdownlint-cli      
    #           markdownlint $(System.DefaultWorkingDirectory)/

    #       displayName: 'MarkdownLint Run'
          
    #   - job: LintBackend
    #     displayName: Lint Python Backend

    #     steps:
    #     - task: PowerShell@2
    #       continueOnError: true
    #       inputs:
    #         targetType: 'inline'
    #         script: |
    #           cd $(backendPath)/
      
    #           # Install dependencies
    #           npm install
              
    #           # Install markdownlint-cli if not in package.json
    #           npm install --save-dev markdownlint-cli
              
    #           # Run markdownlint on all markdown files, excluding node_modules
    #           npx markdownlint "**/*.md" --ignore node_modules

    #       displayName: 'Markdownlint Install & Run'

    #     - task: PowerShell@2
    #       continueOnError: true
    #       inputs:
    #         targetType: 'inline'
    #         script: |
    #           cd $(backendPath)
      
    #           # Install dependencies
    #           npm install
              
    #           # Install textlint and common presets if not in package.json
    #           npm install --save-dev textlint textlint-rule-preset-ja-technical-writing
              
    #           # Run textlint on markdown files
    #           npx textlint "**/*.md"

    #       displayName: 'TextLint Install & Run'

    #     - task: PyLint@0
    #       continueOnError: true
    #       displayName: Run PyLint
    #       inputs:
    #         pythonroot: '$(backendPath)'
    #         reqfile: '$(backendPath)/requirements.txt'
    #         modules: '.'

    #     - task: PowerShell@2
    #       continueOnError: true
    #       inputs:
    #         targetType: 'inline'
    #         script: |
    #           # Install Hadolint (Windows)
    #           Write-Host "Installing Hadolint for Dockerfile linting..."
              
    #           # Method 1: Using Chocolatey (if available)
    #           if (Get-Command choco -ErrorAction SilentlyContinue) {
    #             Write-Host "Installing via Chocolatey..."
    #             choco install hadolint -y
    #           } else {
    #             # Method 2: Download executable directly
    #             Write-Host "Downloading Hadolint executable..."
    #             $hadolintUrl = "https://github.com/hadolint/hadolint/releases/latest/download/hadolint-Windows-x86_64.exe"
    #             $hadolintPath = "$env:TEMP\hadolint.exe"
                
    #             Invoke-WebRequest -Uri $hadolintUrl -OutFile $hadolintPath
                
    #             # Make it available globally
    #             Copy-Item $hadolintPath "$env:ProgramFiles\hadolint\hadolint.exe"
    #             [Environment]::SetEnvironmentVariable("Path", "$env:Path;$env:ProgramFiles\hadolint", "Machine")
    #           }
            
    #           # Run Hadolint on Dockerfiles
    #           Write-Host "Running Hadolint on Dockerfiles..."
              
    #           # Find all Dockerfiles recursively
    #           $dockerfiles = Get-ChildItem -Recurse -Filter "Dockerfile*" -File
              
    #           if ($dockerfiles.Count -eq 0) {
    #             Write-Host "No Dockerfiles found. Skipping Hadolint."
    #             exit 0
    #           }
            
    #           Write-Host "Found $($dockerfiles.Count) Dockerfile(s):"
    #           $dockerfiles | ForEach-Object { Write-Host "  - $($_.FullName)" }
              
    #           # Run Hadolint on each Dockerfile
    #           $errorsFound = $false
    #           foreach ($dockerfile in $dockerfiles) {
    #             Write-Host "`nLinting: $($dockerfile.FullName)"
                
    #             # Run Hadolint
    #             if (Get-Command hadolint -ErrorAction SilentlyContinue) {
    #               hadolint $dockerfile.FullName
    #             } elseif (Test-Path $hadolintPath) {
    #               & $hadolintPath $dockerfile.FullName
    #             } else {
    #               Write-Host "Hadolint not found. Please install manually."
    #               exit 1
    #             }
                
    #             # Check exit code
    #             if ($LASTEXITCODE -ne 0) {
    #               $errorsFound = $true
    #             }
    #           }
            
    #           if ($errorsFound) {
    #             Write-Host "##vso[task.logissue type=error]Hadolint found issues in Dockerfile(s)"
    #             Write-Host "##vso[task.complete result=Failed]"
    #             exit 1
    #           }
              
    #           Write-Host "✅ Hadolint completed successfully!"
              
    #       displayName: 'Install and Run Hadolint'

    - stage: BuildAndPackage
      displayName: Build & Artifact Packaging
      
      jobs:
          - job: FrontendApplicationBuild
            displayName: Frontend Application Build
            
            steps:
            - task: NodeTool@0
              displayName: Set Up Node.js Environment
              inputs:
                versionSource: 'spec'
                versionSpec: '16.x'
            
            - task: PowerShell@2
              displayName: Install Dependencies
              inputs:
                  targetType: inline
                  script: 'npm install'

            - task: PowerShell@2
              displayName: Build Application
              inputs:
                  targetType: inline
                  script: 'npm run build'

            - task: PublishPipelineArtifact@1
              inputs:
                targetPath: '$(System.DefaultWorkingDirectory)/build/'
                artifact: 'todo-ui'
                publishLocation: 'pipeline'

        #   - job: BackendApplicationBuild
        #     displayName: Backend Application Build

