name: Python Basic Check
on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run a Script
        run: |
          echo "Script chal gayi bhai!"
          python --version
